// UI
export const ACTION_SET_THEME = "ACTION_SET_THEME";

// Categories
export const ACTION_CATEGORIES_LOADED = "ACTION_CATEGORIES_LOADED";
export const ACTION_CATEGORIES_START_LOADING = "ACTION_CATEGORIES_START_LOADING";
export const ACTION_CATEGORIES_FAILED_LOAD = "ACTION_CATEGORIES_FAILED_LOAD";
export const ACTION_SELECT_PRODUCT = "ACTION_SELECT_PRODUCT";
export const ACTION_UNSELECT_PRODUCT = "ACTION_UNSELECT_PRODUCT";
export const ACTION_GO_TO_BASKET = "ACTION_GO_TO_BASKET";

// Basket
export const ACTION_ORDER_PRODUCTS = "ACTION_ORDER_PRODUCTS";

